---
title: ""
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'publications.html'))})
output:
  html_document:
    df_print: paged
    css: "style.css"
---


<center>

<h1>Publications</h1>

</center>

</div>

::: {style="margin-bottom:20px;"}
:::

<p style="text-align: center;">
<span style="text-align: center; display: inline-block; color: #4b85d8" class="fa fa-4x fa-file-lines" aria-hidden="true"></span>
<span class="my-text"></span>
</p>

</div>

::: {style="margin-bottom:20px;"}
:::

## Selected Publications

Please see a full list on my [Google Scholar page](https://scholar.google.com/citations?user=-805KJkAAAAJ&hl=en) or my [CV](https://github.com/kimberlywebb/docs/blob/bb03017ee7b208574278a39e336518263558946e/KAH_Webb_CV.pdf?raw=true).

$~$
$~$

#### Preprints and Submitted Papers

-   **KAH Webb**, SA Riley, and MT Wells, "An assessment of racial disparities in pretrial decision-making using misclassification models". [arXiv:2309.08599](https://arxiv.org/abs/2309.08599).

-   **KAH Webb** and MT Wells, "COMBO and COMMA: R packages for regression modeling and inference in the presence of misclassified binary mediator or outcome variables". [arXiv:2501.08320](https://arxiv.org/abs/2501.08320)

$~$


#### Selected Peer-Reviewed Journal Articles

-   **KAH Webb** and MT Wells, "Effect estimation in the presence of a misclassified binary mediator". March 2025. *Statistical Methods in Medical Research*. [doi:10.1177/09622802251316970](https://journals.sagepub.com/eprint/PW4ZRM9CUAR5GIBGTWFT/full)

     - See the visual abstract for this paper [here](https://github.com/kimberlywebb/docs/blob/2e45ae76056483d4f8868eb99b80f1e19bab1694/Webb_mediation_SMMR_visual_abstract.png). 
     
</div>

-   **KAH Webb** and MT Wells, "Statistical inference for association studies in the presence of binary outcome misclassification". February 2025. *Statistics in Medicine*. [DOI:10.1002/sim.10316](https://onlinelibrary.wiley.com/doi/10.1002/sim.10316)

     - See the visual abstract for this paper [here](https://github.com/kimberlywebb/docs/blob/5c53226296f2e11db48d7523db1f17065b07f75e/SiM2025_VisualAbstract.png). 
     
</div>

-   **KA Hochstedler**${^*}$, F Fang${^*}$, R Tamura, T Braun, K Kidwell. "Bayesian methods to compare dose levels to placebo in a small n sequential multiple assignment randomized trial (snSMART)" February 2021. *Statistics in Medicine* [DOI:10.1002/sim.8813](https://doi.org/10.1002/sim.8813)

    -   $*$ Denotes co-first author.

</div>

-   JR Wilkie, **KA Hochstedler**, MJ Schipper, MM Matuszak, P Paximadis, MM Dominello, I Grills, JA Hayman, R Dess, AF Dragovic, R Jagsi, LJ Pierce, DE Spratt, D Bergsma, TP Boike, B Movsas, S Jolly. "Association between physician- and patient-reported symptoms in patients treated with definitive radiation therapy for locally advanced lung cancer in a statewide consortium." March 2022. *International Journal of Radiation Oncology-Biology-Physics*. [DOI: 10.1016/j.ijrobp.2021.11.024](https://doi.org/10.1016/j.ijrobp.2021.11.024)

-   **KA Hochstedler**, G Bell, H Park, A Ghassabian, E Bell, R Sundaram, K Grantz, E Yeung. "Gestational Age at Birth and Early Childhood Development: the Upstate KIDS Study." March 2020. *American Journal of Perinatology*. [DOI: 10.1055/s-0040-1702937](https://www.thieme-connect.com/products/ejournals/html/10.1055/s-0040-1702937)

    -   This work was discussed in [this New York Times piece](https://www.nytimes.com/2020/06/08/well/family/premature-babies-preterm-birth-pregnancy-developmental-delays.html).
