---
title: ""
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'teaching.html'))})
output:
  html_document:
    df_print: paged
    css: "style.css"
---

<center> <h1>Teaching</h1> </center>

</div>
<div style="margin-bottom:20px;">
</div>

<p style="text-align: center;">
<span style="text-align: center; display: inline-block; color: #4b85d8" class="fa fa-4x fa-chalkboard-teacher" aria-hidden="true"></span>
<span class="my-text"></span>
</p>

</div>
<div style="margin-bottom:20px;">
</div>


## Teaching Philosophy
As an instructor of statistics, my goal is to prepare students to apply their quantitative skills to their interests, passions, and problems. It is important that I prepare students to approach problems holistically and in context. I plan to achieve this goal through: 

- Hands-on experiences with real-world data   
- Exposure to a variety of statistical applications   

I believe that bringing multiple perspectives to the classroom and allowing students to have personal choice in projects and datasets facilitates an inclusive and relevant learning environment.   
    
</div>
<div style="margin-bottom:30px;">
</div>

<p style="text-align: center;">
<span style="text-align: center; display: inline-block;" class="fa fa-2x fa-comment-dots" aria-hidden="true"></span>
<span class="my-text">[Teaching Philosophy](https://raw.github.com/kimhochstedler/documents/master/KAH_Webb_TeachingStatement.pdf)</span>
</p>

<p style="text-align: center;">
<span style="text-align: center; display: inline-block;" class="fa fa-2x fa-pen-clip" aria-hidden="true"></span>
<span class="my-text">[Sample Syllabus](https://raw.github.com/kimhochstedler/documents/master/sample_syllabus.pdf)</span>
</p>

<p style="text-align: center;">
<span style="text-align: center; display: inline-block;" class="fa fa-2x fa-bar-chart" aria-hidden="true"></span>
<span class="my-text">[Teaching Demonstration Slides](https://raw.github.com/kimhochstedler/documents/master/teaching_demo_slides.pptx)</span>
</p>

<p style="text-align: center;">
<span style="text-align: center; display: inline-block;" class="fa fa-2x fa-folder" aria-hidden="true"></span>
<span class="my-text">[Teaching Portfolio](https://kimberlywebb.github.io/teaching_portfolio/)</span>
</p>

</div>
<div style="margin-bottom:30px;">
</div>


## Teaching Experience
- Senior Lead Fellow in Cornell University's Center for Teaching Innovation [Graduate Teaching Fellowship](https://teaching.cornell.edu/cti-graduate-teaching-fellowship) Program for 2023-2024.

- Co-creator and co-facilitator of the [Advanced Graduate Teaching Cohort](https://teaching.cornell.edu/advanced-graduate-teaching-cohort) Program for 2023. 

- Lead Fellow in Cornell University's Center for Teaching Innovation [Graduate Teaching Fellowship](https://teaching.cornell.edu/cti-graduate-teaching-fellowship) Program for 2022-2023.

- Fellow in Cornell University's Center for Teaching Innovation [Graduate Teaching Fellowship](https://teaching.cornell.edu/cti-graduate-teaching-fellowship) Program for 2021-2022.

- Graduate Teaching Assistant for *Introductory Statistics* (online), taught by [Thomas DiCiccio, Ph.D.](https://www.ilr.cornell.edu/people/thomas-diciccio) at Cornell University, January 2022, June 2022, and January 2023.

- Graduate Teaching Assistant for *Biological Statistics II* (online), taught by [Jeremy Entner, Ph.D.](https://stat.cornell.edu/people/faculty/jeremy-entner) at Cornell University, Spring 2021.

- Graduate Teaching Assistant for *Statistical Methods I* (graduate level, online), taught by [Sumanta Basu, Ph.D.](http://faculty.bscb.cornell.edu/~basu/) at Cornell University, Fall 2020.

- Course Designer for *Hungry in America - Building Skills to Feed Communities*, taught by [Susan Aaronson, M.A., R.D.](https://sph.umich.edu/faculty-profiles/aaronson-susan.html) and [Kate Bauer, Ph.D.](https://sph.umich.edu/faculty-profiles/bauer-kate.html) at the University of Michigan, Spring 2020.    

- Student in *Effective Teaching in Public Health*, taught by [Olivia Anderson, Ph.D.](https://sph.umich.edu/faculty-profiles/anderson-olivia.html) at the University of Michigan, Fall 2019.

- Student Coordinator with the [Big Data Summer Institute](https://sph.umich.edu/bdsi/about/index.html) at the University of Michigan, Summer 2019.

- Undergraduate Teaching Assistant for *Social Psychology* with [Vicki Helgeson, Ph.D.](https://www.cmu.edu/dietrich/psychology/people/core-training-faculty/helgeson-vicki.html) at Carnegie Mellon University, Fall 2017. 

- Undergraduate Teaching Assistant for *Biological Foundations of Behavior* with [Marlene Behrmann, Ph.D.](https://www.cmu.edu/dietrich/psychology/people/core-training-faculty/behrmann-marlene.html) at Carnegie Mellon University, Spring 2018.